kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-nginx-ingress
  namespace: ingress
data:
  proxy-connect-timeout: "10s"
  proxy-read-timeout: "10s"
  client-max-body-size: "2m"
  no-tls-redirect-locations: "/.well-known/acme-challenge"